sonar.projectKey=deefy
sonar.projectName=Deefy
sonar.sourceEncoding=UTF-8
sonar.sources=backend/src/main,frontend/src
sonar.tests=backend/src/test
sonar.exclusions=**/*.png,**/*.svg,**/*.jpg,**/*.ico
sonar.java.binaries=backend/target/classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
