CREATE TABLE IF NOT EXISTS PLAYLIST_COMPARTILHADA (
    id SERIAL PRIMARY KEY,
    playlist_id INT NOT NULL,
    usuario_id INT NOT NULL,
    permissao VARCHAR(30) NOT NULL,
    origem VARCHAR(20),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (playlist_id) REFERENCES PLAYLIST(id) ON DELETE CASCADE,
    FOREIGN KEY (usuario_id) REFERENCES USUARIO(id) ON DELETE CASCADE,
    UNIQUE(playlist_id, usuario_id)
);
